import Head from "next/head";
import PageTemplate from "@/components/PageTemplate";
import Container from "@/components/Container";
import ProgramCard from "@/components/cards/ProgramCard";
import Section from "@/components/Section";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [countUp, setCountUp] = useState(0);

  const keyDownEvent = (event: React.KeyboardEvent<HTMLDivElement>) => {
    console.log(event.code);
    if (event.code === "ArrowUp") {
      setCountUp(() => countUp + 1);
    }
  };

  const landingPage = (
    <Section>
      <div
        className="min-h-screen w-screen bg-royal-blue grid place-items-center"
        onKeyDown={keyDownEvent}
        tabIndex={0}
      >
        <h1 className="text-heading-1  text-gray-1 ">COMING SOON</h1>
      </div>
    </Section>
  );

  if (countUp < 3) {
    return landingPage;
  }

  return (
    <div>
      <Head>
        <title>Phi Beta Sigma: The Bahamas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTemplate>
        <header className="pt-12 pb-40 bg-gray-2">
          <Container>
            <h1 className="text-heading-1 text-gray-6">
              Brotherhood. <br />
              Scholarship. <br />
              Service.
            </h1>
          </Container>
        </header>
        <Section>
          <div className="gap-x-6 flex flex-col-reverse lg:flex-row">
            <div className="lg:w-1/2 w-full">
              <h4 className="text-heading-4 text-gray-6 mt-4 lg:mt-0">About</h4>
              <p className="text-gray-5 pt-1">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Aspernatur sit earum et aperiam, dolore eveniet eius rem itaque
                temporibus dolor enim quae cupiditate voluptates quas fugiat
                hic, obcaecati quis natus recusandae in? Veritatis molestias id
                facilis rem ipsam laborum, tempora cumque numquam quas porro non
                saepe earum officia dolorum doloribus delectus ducimus sapiente
                provident doloremque! Assumenda impedit in cupiditate maxime
                dolorem? Dicta sed nobis molestiae officiis, architecto magnam
                numquam id harum suscipit aliquid nulla quod ratione quae odio
                dolore molestias doloribus facere necessitatibus aperiam
                reprehenderit doloremque cum quos fugit. Suscipit alias ad
                repellat saepe quia, iste incidunt facere nulla iure!
              </p>
              <Link
                href="https://phibetasigma1914.org/about/history/"
                target="_blank"
                className="cursor-pointer"
              >
                <button className="cursor-pointer rounded bg-royal-blue text-heading-6 text-gray-1 py-2 px-6 uppercase mt-6">
                  Learn more{" "}
                </button>
              </Link>
            </div>
            <div className="grow bg-[#F0F0F0]">
              <img
                src={"/images/empty.png"}
                alt="Our mission"
                className="h-full mx-auto"
              />
            </div>
          </div>
        </Section>
        <Section classes="bg-gray-2">
          <div className="gap-x-6 flex lg:flex-row flex-col">
            <div className="grow bg-[#F0F0F0]">
              <img
                src={"/images/empty.png"}
                alt="Our mission"
                className="h-full mx-auto"
              />
            </div>
            <div className="lg:w-1/2 w-full">
              <h4 className="text-heading-4 text-gray-6 lg:mt-0 mt-4">
                Our mission
              </h4>
              <p className="text-gray-5 pt-1">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                Aspernatur sit earum et aperiam, dolore eveniet eius rem itaque
                temporibus dolor enim quae cupiditate voluptates quas fugiat
                hic, obcaecati quis natus recusandae in? Veritatis molestias id
                facilis rem ipsam laborum, tempora cumque numquam quas porro non
                saepe earum officia dolorum doloribus delectus ducimus sapiente
                provident doloremque! Assumenda impedit in cupiditate maxime
                dolorem? Dicta sed nobis molestiae officiis, architecto magnam
                numquam id harum suscipit aliquid nulla quod ratione quae odio
                dolore molestias doloribus facere necessitatibus aperiam
                reprehenderit doloremque cum quos fugit. Suscipit alias ad
                repellat saepe quia, iste incidunt facere nulla iure!
              </p>
              <Link
                href="https://phibetasigma1914.org/about/history/"
                target="_blank"
                className="cursor-pointer"
              >
                <button className="cursor-pointer rounded bg-royal-blue text-heading-6 text-gray-1 py-2 px-6 uppercase mt-6">
                  Learn more
                </button>
              </Link>
            </div>
          </div>
        </Section>
        <section className="py-12 bg-[#E7EFFF]">
          <Container>
            <div className="gap-x-4 flex w-full flex-wrap lg:flex-nowrap flex-col sm:flex-row">
              <ProgramCard title="Bigger Better Business" photoUrl="" />
              <ProgramCard title="Bigger Better Business" photoUrl="" />
              <ProgramCard title="Bigger Better Business" photoUrl="" />
              <ProgramCard title="Bigger Better Business" photoUrl="" />
            </div>
          </Container>
        </section>
      </PageTemplate>
    </div>
  );
}
