import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navigation/Navbar'
import Footer from '@/components/navigation/Footer'
import PageTemplate from '@/components/PageTemplate'
import Container from '@/components/Container'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Phi Beta Sigma: The Bahamas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTemplate>
        <header className='pt-12 pb-40 bg-gray-2'>
          <Container>
            <h1 className='text-heading-1 text-gray-6'>
              BrotherHood. <br />
              Scholarship. <br />
              Service.
            </h1>
          </Container>
        </header>
        <section className='py-12'>
          <Container>
            <div className="gap-x-6 flex">
              <div className='w-1/2'>
                <h4 className="text-heading-4 text-gray-6">About</h4>
                <p className="text-gray-5 pt-1">
                  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur sit earum et aperiam, dolore eveniet eius rem itaque temporibus dolor enim quae cupiditate voluptates quas fugiat hic, obcaecati quis natus recusandae in? Veritatis molestias id facilis rem ipsam laborum, tempora cumque numquam quas porro non saepe earum officia dolorum doloribus delectus ducimus sapiente provident doloremque! Assumenda impedit in cupiditate maxime dolorem? Dicta sed nobis molestiae officiis, architecto magnam numquam id harum suscipit aliquid nulla quod ratione quae odio dolore molestias doloribus facere necessitatibus aperiam reprehenderit doloremque cum quos fugit. Suscipit alias ad repellat saepe quia, iste incidunt facere nulla iure!
                </p>
                <button className='rounded bg-royal-blue text-heading-6 text-gray-1 py-1 px-6 uppercase mt-6'>Learn more</button>
              </div>
              <div className='grow bg-gray-2'>
                PICTURE
              </div>
            </div>
          </Container>
        </section>
        <section className="py-12 bg-gray-2">
          <Container>
            <div className="gap-x-6 flex">
              <div className='grow bg-gray-1'>
                  PICTURE
              </div>
              <div className='w-1/2'>
                <h4 className="text-heading-4 text-gray-6">Our mission</h4>
                <p className="text-gray-5 pt-1">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur sit earum et aperiam, dolore eveniet eius rem itaque temporibus dolor enim quae cupiditate voluptates quas fugiat hic, obcaecati quis natus recusandae in? Veritatis molestias id facilis rem ipsam laborum, tempora cumque numquam quas porro non saepe earum officia dolorum doloribus delectus ducimus sapiente provident doloremque! Assumenda impedit in cupiditate maxime dolorem? Dicta sed nobis molestiae officiis, architecto magnam numquam id harum suscipit aliquid nulla quod ratione quae odio dolore molestias doloribus facere necessitatibus aperiam reprehenderit doloremque cum quos fugit. Suscipit alias ad repellat saepe quia, iste incidunt facere nulla iure!
                </p>
                <button className='rounded bg-royal-blue text-heading-6 text-gray-1 py-1 px-6 uppercase mt-6'>Learn more</button>
              </div>
            </div>
          </Container>
        </section>
        <section className="py-12 bg-[#E7EFFF]">
          <Container>
            <div className="gap-x-4 flex w-full">
              <div className="rounded w-1/4 h-72 bg-gray-3">
                <div className="bg-gray-2 w-full h-5/6"> ssdsdsds</div>
                <h5 className="text-heading-5">Hello </h5>
              </div>
            </div>
          </Container>
        </section>
      </PageTemplate>
    </>
  )
}
