name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile.prod --tag ${{ secrets.DOCKER_USERNAME }}/pbs-bahamas-state-frontend:latest --build-arg NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}} --build-arg NEXT_PUBLIC_TOKEN=${{secrets.NEXT_PUBLIC_TOKEN}}

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pbs-bahamas-state-frontend:latest
